### PR TITLE
improve uvc with import/export of config parameters

### PR DESCRIPTION
**Pull request by mgrzeschik**

### CODE REVIEW

**Comment by mgrzeschik** [comment]
I fixed the commit typos.

But, from your earlier post:

"Please also compare results for cppcheck, scan-build and GCC -fanalyzer
static analysis runs before and after the commits."

Is there some automatic way to do that?

**Comment by pabs3** [comment]
I don't think there is a way to automate the comparison between results
for branches. I usually just run them against master saving results to
a file, checkout the branch, run them again saving results to a file
and then compare them with diff or meld. For GCC -fanalyzer I think you
just need to do a build with -fanalyzer in the CFLAGS.

These are the commands: 

```
$ cppcheck -j1 --quiet .
$ cppcheck -j1 --quiet --enable=warning .
$ cppcheck -j1 --quiet --enable=all .
$ cppcheck -j1 --quiet --enable=all --force .
```

```
$ scan-build make
```

```
make CFLAGS=-fanalyzer
```

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by pabs3** [comment]
@mgrzeschik in #47 it was proposed to make a new release, do you want to finish including this PR before we do that, or wait until after the release to do that?

**Comment by mriesch-wv** [comment]
AFAIAC having this PR in the new release would be great!

Thanks a lot in advance :-)

**Pull request merged**
